package org.geysermc.packgenerator;

import org.geysermc.packgenerator.pack.BedrockVersion;

public class PackConstants {
    public static final String DEFAULT_PACK_DESCRIPTION = "A resourcepack generated by " + GeyserMappingsGenerator.NAME;
    public static final BedrockVersion ENGINE_VERSION = BedrockVersion.of(1, 21, 0);
}
