package org.geysermc.rainbow;

import org.geysermc.rainbow.pack.BedrockVersion;

public class PackConstants {
    public static final String DEFAULT_PACK_DESCRIPTION = "A resourcepack generated by " + Rainbow.MOD_NAME;
    public static final BedrockVersion ENGINE_VERSION = BedrockVersion.of(1, 21, 0);
}
